chore: 19762 - can't use ubi8-minimal:8.4 and then install golang as Brew builds fail with (#876)
error: No available modular metadata for modular package 'golang-1.15.7-1.module+el8.4.0+9580+3b0e6c24.ppc64le'; cannot be installed on the system

Change-Id: If0dc121ed855da22cea36d078dd6df05a340e66d
Signed-off-by: nickboldt <nboldt@redhat.com>

don't need to install bzip2 or unzip; already in the go toolset image

Change-Id: If6110970de17482c1c1c39f5b5fe0f094f7d74e8
Signed-off-by: nickboldt <nboldt@redhat.com>